### ISSUE TITLE
[Request] Ability to pass vector inputs to `Classify`

### ISSUE THREAD

**Issue by guillochon** [daniel-muthukrishna/astrodash#3]
It would be great to pass a Nx2 (or Nx3) array into `Classify` rather than a filename, for use in other packages where the spectrum might already be loaded into memory.

**Comment by guillochon** [comment]
Hi @daniel-muthukrishna, revising this request slightly: It would be great to just be able to pass a file *handle* into `Classify`, I think this would just require you to add an additional switch in `file_extension` that checks if the input is a file handle.

The reason for this is this way the user can create a temporary file, in memory, that can be passed to dash to classify, as it is now the spectrum has to be written to disk first before dash can be used on it, which is not optimal.

**Comment by daniel-muthukrishna** [comment]
Hi @guillochon, I have just updated the project to fulfil both of your requests (i.e accept Nx2 array, accept file-handle or accept a filename).
I'm currently training some new models (that train on SLSN and also use a different wavelength range) which mean that the current GitHub version may be unstable. I'll upload the new models along with the new functionality to PyPI sometime next week.

The example script I used to test this new functionality is as follows:
`import dash
import numpy as np

wave = np.arange(2500, 10000, 2)
flux = np.ones(len(wave))
filename = np.array([wave, flux])
# filename = open('/Users/danmuth/PycharmProjects/DASH/templates/superfit_templates/sne/Ib/sn1983N.p12.dat', 'r')

classification = dash.Classify([filename], [0.], classifyHost=False, rlapScores=True)
bestFits, redshifts, bestTypes, rlapFlag, matchesFlag = classification.list_best_matches(n=5)

print(bestFits)

classification.plot_with_gui(indexToPlot=0)`

Cheers

**Comment by guillochon** [comment]
Beautiful, thanks @daniel-muthukrishna!

P.S. The OSC has an API now that can be used to retrieve spectra. Format is JSON but is pretty simple to parse. Example: https://api.sne.space/SN1978K/spectra/time+data

Might be nice to add a little reader that works directly with that format?

**Comment by guillochon** [comment]
Adding to this: Here's a little script I put together based on your example that classifies a spectrum available on the OSC. Maybe gives some idea on how this could be implemented. https://github.com/guillochon/dashtest

(and yes it does return the right type/epoch!)

**Comment by daniel-muthukrishna** [comment]
Done!
You can add an input from the OSC with a name in the following format: 'os-name-ageIndex'
Example here:
```
import dash
import numpy as np

filename = 'osc-SN2002er-10'
redshift = 'osc'   # can be 'osc' or any other number, but redshift will be taken from the catalog

classification = dash.Classify([filename], [redshift], classifyHost=False, rlapScores=True)
bestFits, redshifts, bestTypes, rlapFlag, matchesFlag = classification.list_best_matches(n=5)

print(bestFits)

classification.plot_with_gui(indexToPlot=0)
```

Alos thanks, it's good to know about the convenient OSC API. Does the OSC have any data on the (best-fit) date of maximum light for each SN (giving us epoch) by any chance? If so, it might make a great addition to the DASH training set with known type/epoch.

**Comment by guillochon** [comment]
Amaaaaaazing! This is great!

There is a date of maximum tagged on most SNe with photometry, if it was computed in the lit that’s the value that appears, otherwise we calculate it in a rather crude way (its usually just the time of the brightest obs). The attributes are either `maxdate` (uses all bands) or `maxvisualdate` (uses only visual bands).
